name: tmux-non-dead # you probably want to 'snapcraft register <name>'
version: '3.2-rc'
summary: Access and control terminals (or windows) from a single terminal.
description: |
        tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
        to be accessed and controlled from a single terminal. tmux is intended to be a
        simple, modern, BSD-licensed alternative to programs such as GNU screen.

#grade: stable # must be 'stable' to release into candidate/stable channels
grade: stable 
confinement: devmode # use strict or devmode
base: core18

architectures:
  - build-on: [amd64, armhf]
    run-on: [armhf, arm64, amd64]
        
apps:
        tmux:
#                command: /bin/tmux
                command: tmux

parts:
        tmux:
                plugin: autotools
                source: https://github.com/tmux/tmux/releases/download/3.2/tmux-3.2-rc.tar.gz

                build-packages:
                        - libevent-dev
                        #- libncursesw5-dev
                        - libncurses-dev
                        - libtinfo5
                stage-packages:
                        - libevent-dev
                        #- libncursesw5-dev
                        - libncurses-dev
                #command: tmux
                organize: 
                        tmux: bin/
