name: tmux-non-dead # you probably want to 'snapcraft register <name>'
version: '2.7'
summary: Access and control terminals (or windows) from a single terminal.
description: |
        tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
        to be accessed and controlled from a single terminal. tmux is intended to be a
        simple, modern, BSD-licensed alternative to programs such as GNU screen.
#type: app

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


architectures:
        - armhf
        - arm64
        - amd64

apps:
        tmux:
                #command: /bin/tmux
                command: tmux

#Requires at least a:
# working C compiler, make, autoconf, automake,
# pkg-config as well as libevent and ncurses libraries and headers.

parts:
        tmux:
                plugin: autotools
                source: https://github.com/tmux/tmux/releases/download/2.7/tmux-2.7.tar.gz

                stage-packages:
                        - libc6
                        - libevent-dev
                        - libncurses-dev
